name = "ranger"
version = "1.2.0"

description = "create ranges over any type"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [{ title = "Gleam", href = "https://gleam.run" }]
repository = { type = "github", user = "massivefermion", repo = "ranger" }

[dependencies]
gleam_stdlib = "~> 0.36 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
